name: trading_app
description: A Flutter trading app
publish_to: none
version: 1.0.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^2.4.0
  syncfusion_flutter_charts: ^25.1.35

flutter:
  uses-material-design: true
